### PR TITLE
fix: flush logs on package resolution failure

### PR DESCRIPTION
**Pull request by skywalker512**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/terminus/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Thanks for this PR! What is the motivation behind this change?

**Comment by skywalker512** [comment]
> Thanks for this PR! What is the motivation behind this change?

Like https://github.com/nestjs/nest/pull/8278 , if dependencies such as typeorm are not installed when bufferLogs is turned on, it will be exit(1) without an error. Here flush log can output the error message normally.

**Comment by BrunnerLivio** [comment]
Gotcha, LGTM

**Comment by BrunnerLivio** [comment]
Released with [v9.1.2](https://github.com/nestjs/terminus/releases/tag/9.1.2) by @skywalker512 🎉

**Pull request merged**
