### PR TITLE
chore: additional exports

### PR DESCRIPTION
**Pull request by htndev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
No HealthCheckExecutor import

Issue Number: N/A

## What is the new behavior?
Additional export

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
What is the motivation behind this change?

**Comment by htndev** [comment]
@BrunnerLivio In our dev team, we are writing a custom wrapper on the ``TerminusModule`` and we need to import ``HealthCheckExecutor`` from the ``dist`` folder.  Just for a beautiful import 😃

**Comment by BrunnerLivio** [comment]
@htndev I did not plan to expose the `HealtCheckExecutor` as part of the public API. Public API means for me that if I change the behavior, I'll need to introduce a breaking change. So I am cautious with adding anything there. 

Could you give more context around this, so I can understand why you'd need to use that executor? Can't you just build a wrapper around [`HealthCheckService`](https://github.com/nestjs/terminus/blob/master/lib/health-check/health-check.service.ts)?

**Comment by htndev** [comment]
@BrunnerLivio When I'm writing my custom wrapper, I can't provide TerminusModule exports. Maybe, I need to rethink the logic. Can this pr pend a little bit?

**Comment by BrunnerLivio** [comment]
@htndev sure no worries!

**Comment by htndev** [comment]
@BrunnerLivio Hi. I rewrite our module and this export is useless now. I'm closing PR.

**Pull request closed without merging**
