### PR TITLE
bugfix: fix incorrect microservice-configuration.interface import

### PR DESCRIPTION
**Pull request by BenWildeman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #606 606

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Is included in #593, thanks anyway!

**Comment by BenWildeman** [comment]
@BrunnerLivio instead of waiting for v7 of this which introduces breaking changes, this should be merged instead to fix compatibility. we need a fix now for people already using v6, not wait for a v7 of this. your PR is still WIP and there's no timeframe on when it's done

**Comment by BenWildeman** [comment]
@BrunnerLivio instead of waiting for v7 of this which introduces breaking changes, this should be merged instead to fix compatibility. we need a fix now for people already using v6, not wait for a v7 of this. your PR is still WIP and there's no timeframe on when it's done

**Comment by BrunnerLivio** [comment]
I am planning to release working v7 prerelease tomorrow - in case I am unable to publish that until then I will release a new v6 patch release with this change. So you will have a working version by tomorrow in any case.
Sounds good? @BenWildeman

**Comment by BenWildeman** [comment]
good enough.

**Comment by BrunnerLivio** [comment]
@BenWildeman

There is already `@nestjs/terminus@7.0.0-pre.2`. 

Make sure you have

- `skipLibCheck` in your `tsconfig.json
- `@godaddy/terminus` installed

I will fix the points above asap. 

Have fun, contact me in case you encounter any bugs or strange behaviors!

**Pull request closed without merging**
