### PR TITLE
added HttpResponseIndicator

### PR DESCRIPTION
**Pull request by trescube**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

*Do you want a sample app, too?*

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #984 

## What is the new behavior?

Adds a general HTTP response health indicator that accepts a callback and returns `true`/`false` indicating the health of the service.  The callback returns either a `boolean` or `Promise<boolean>` for asynchronous operations.  

Proper setup and parsing of the response is left up to the implementer, this just supplies the tool to make the HTTP call and return `HealthIndicatorResult` based on the return of the callback to reduce boilerplate code.  

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### Elasticsearch Example

An example of this indicator in action would is:

```
function elasticsearchIsHealthy (catHealthResponse: Record<string,any>) {
  return catHealthResponse.status === 'green';
}

@Get()
@HealthCheck()
check (): Promise<HealthCheckResult> {
  this.logger.verbose('Performing health checks');

  return this.health.check([
    async () => this.httpResponse.checkResponse<Record<string,any>>(
      'elasticsearch', 
      'http://localhost:9200/_cat/health', 
      elasticsearchIsHealthy)
  ]);
}
```

### Kafka Connect Example

Another example would be checking the health of a Kafka sink connector which has a REST API that can be queried for health.  This API returns the following response in the case of a working connector:

```
curl http://127.0.0.1:8083/connectors/sink-elastic-index-documents/status | jq '.'

{
  "name": "sink-elastic-index-documents",
  "connector": {
    "state": "RUNNING",
    "worker_id": "connect:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "RUNNING",
      "worker_id": "connect:8083"
    }
  ],
  "type": "sink"
}
```

To check the health of the Kafka sink connector:

```
function kafkaConnectorIsHealthy (statusResponse: ConnectorStatusResponse) {
  return statusResponse.tasks[0].state === 'RUNNING';
}

@Get()
@HealthCheck()
check (): Promise<HealthCheckResult> {
  this.logger.verbose('Performing health checks');

  return this.health.check([
    async () => this.httpResponse.checkResponse<ConnectorStatusResponse)>(
      'kafka-connect-sink', 
      'http://127.0.0.1:8083/connectors/sink-elastic-index-documents/status', 
      kafkaConnectorIsHealthy)
  ]);
}
```

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Thank you for this change request. I think it makes sense to add this functionality. What do you think about refactoring this into the `DNSHealthIndiciator` instead, since the functionality is very similar. I am aware that "DNS" is not really the best term to describe this functionality, but I am thinking about renaming this health indicator to `HTTPHealthIndicator` anyway.


So the public API would look something like this:

```typescript
interface DNSHealthIndicator {
  async pingCheck(key: string, url: string, options: AxiosRequestConfig = {}): Promise<HealthIndicatorResult>;
  async responseCheck<T>(
    key: string,
    url: URL | string,
    callback: (response: AxiosResponse<T>) => boolean | Promise<boolean>,
    options: AxiosRequestConfig = {},
  ): Promise<HealthIndicatorResult>;
}
```

Note: I think it makes more sense to call it `responseCheck` instead of `checkResponse` to be consistent with `pingCheck`.

What do you think?

**Comment by trescube** [comment]
Sounds good, I like that idea, I'll update!

The cleanest way to combine DNS and HTTP indicators would probably be to combine into the latter and expose the former as an alternate name to the latter (perhaps with a `@Deprecated` decorator, though this may not actually exist in nestjs) since the indicator is growing beyond its original intent.  

As an aside, the name `DNSHealthIndicator` implies that something DNS-related will happen with the inputs whereas it currently returns success as long as a 2xx response is returned and returns failure otherwise for any reason (5xx, 4xx, connection reset, DNS lookup failure, etc - whatever the axios client interprets as an error).  The verb `ping` in this case sounds like it's just performing a reachability check of the host whereas its doing much more.

**Comment by trescube** [comment]
I've updated and included as a `responseCheck` function into DNSHealthIndicator.

**Comment by trescube** [comment]
@BrunnerLivio Thoughts on this?

**Comment by BrunnerLivio** [comment]
Sorry for the delay. Thanks a lot @trescube!

**Pull request merged**
